name: Run API tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          sparse-checkout: 'frontend/'
          sparse-checkout-cone-mode: false
      
      - name: Set up Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
