name: Build and Push Containers to AWS ECR

on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URI }}

      - name: Build backend Docker image
        run: docker build -t bookshelf-express-api ./backend

      - name: Build frontend Docker image
        run: docker build -t bookshelf-astro-app ./frontend

      - name: Tag both images for ECR
        run: |
          docker tag bookshelf-express-api:latest ${{ secrets.ECR_REPO_URI }}/backend:latest && \
          docker tag bookshelf-astro-app:latest ${{ secrets.ECR_REPO_URI }}/frontend:latest
          
      - name: Push both images to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URI }}/backend:latest && \
          docker push ${{ secrets.ECR_REPO_URI }}/frontend:latest
          