name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  application-test:
    runs-on: ubuntu-latest
    services:
      mongo:
          image: mongo
          ports:
            - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Set up Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 'latest'

      - name: Install frontend dependencies
        run: cd frontend/ && npm install

      - name: Run frontend tests
        run: cd frontend/ && npm test
        env: 
          PUBLIC_API_URL: http://localhost:3000

      - name: Install backend dependencies
        run: cd backend/ && npm install

      - name: Run backend tests
        run: cd backend/ && npm test
        
